console.log('This site was generated by Hugo.');

// js.Build use this as a module, so it is necessary to export function

// scroll
function scrollToTop() {
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

function scrollToBottom() {
    window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });
}


//toggle
function toggle(id) {
    var el = document.getElementById(id);
    if (!el) return;

    var current = window.getComputedStyle(el).display;
    el.style.display = (current === 'none') ? 'block' : 'none';
}

// Collect titles
function collectTitles() {
    const elements = document.querySelectorAll(".ctt-main-content .article-main h1, .ctt-main-content .article-main h2, .addto-second-navbar");

    elements.forEach((el, i) => {
        if (el.id !== "title") {
            const id = "sidebar_secondary_id_" + i;
            el.id = id;

            const tag = el.tagName.toLowerCase();
            const link = document.createElement(tag);
            const a = document.createElement("a");
            a.href = "#" + id;
            a.innerHTML = el.innerHTML;
            link.appendChild(a);

            document.getElementById("sidebar-secondary")?.appendChild(link);
        }
    });
}
