---
title: Joining a list of data frames with `Reduce()`
date: 2026-02-11
tags: [R, join, Reduce]
---

Last week, I was working on an R script in which I generated a list of data
frames and was looking for a way to join them quickly. I thought I would be able to leverage `do.call()` but I found this thread on [StackOverflow](https://stackoverflow.com/questions/66360589/how-to-recursively-join-nested-lists-that-share-one-column-name-in-r) that suggested using `Reduce()` to do that and it worked very well.

`Reduce()` is one of the *"Common Higher-Order Functions in Functional Programming Languages"*, a set of functions that are more advanced, maybe not super friendly to use at first, but very powerful!

> ‘Reduce’ uses a binary function to successively combine the 
> elements of a given vector and a possibly given initial value

Here is a simple example, a simplified version of what I was working on:


```{R}
vrbl <- c("pH", "salinity", "temperature")
site <- paste0("site", 1:6)

ls_df <- vrbl |> lapply(\(x) {
    out <- data.frame(site = site)
    out[[x]] <- runif(6)
    out
})
ls_df
```

Note that I often work with lists and `lapply()`, this is very powerful and 
here it is again: to do the join of all data frames, I call `Reduce()` and `inner_join()` 
(from `dplyr`) to do the join:

```{R}
ls_df |> Reduce(f = dplyr::inner_join)
```

Done, I love this! 

<details>
<summary>Session Information</summary>
```{R}
sessionInfo()
```
</details>